# -*- coding: utf-8 -*-
"""
Módulo de Checklists
Contiene la base de datos de preguntas (items de revisión) y el mapeo
de qué preguntas aplican a cada tipo de atención.
"""

# Catálogo completo de las 39 preguntas del sistema original
PREGUNTAS_MASTER = {
    1: "DOCUMENTO DE ASIGNACIÓN DE ORDEN DE TRABAJO CARGADO CORRECTAMENTE AL SCM",
    2: "DOCUMENTOS DE SEGURIDAD SEGÚN TIPO DE TRABAJO CARGADOS CORRECTAMENTE AL SCM",
    3: "INFORMACIÓN CORRECTA DE: TIPO DE ATENCIÓN (RUTINA, REFORMA O REFORMA SUSTANCIAL), TIPO DE CONEXIÓN (SUBTERRÁNEA O AÉREA) Y DETALLES DE ACOMETIDA",
    4: "ALCANCES DEL PROYECTO CARGADOS AL SCM (INFORMACIÓN DEL CLIENTE, CROQUIS Y CUADRO DE CARGAS ENTREGADOS POR ÁREA COMERCIAL)",
    5: "FORMATO DE CALIDAD FIRMADO POR REVISOR A CARGO DE LA CONTRATISTA SE ENCUENTRA CARGADO EN SCM",
    6: "MEMORIA DESCRIPTIVA VIGENTE, COMPLETA Y CON FOTOS POR CADA DISTRITO QUE INTERVENGA EN EL PROYECTO",
    7: "CÁLCULOS DE CAIDA DE TENSIÓN Y DE CAPACIDAD DE CABLES REALIZADOS CORRECTAMENTE Y CARGADOS AL SCM",
    8: "CÁLCULOS MECÁNICOS REALIZADOS CORRECTAMENTE Y CARGADOS AL SCM",
    9: "CÁLCULOS DE ILUMINACIÓN REALIZADOS (LUMINANCIA, ILUMINANCIA, UNIFORMIDADES, ETC) CORRECTAMENTE Y CARGADOS AL SCM",
    10: "CÁLCULOS DE CORTOCIRCUITO REALIZADOS (EN RED y SED'S) CORRECTAMENTE Y CARGADOS AL SCM",
    11: "CÁLCULOS DE PUESTA A TIERRA REALIZADOS CORRECTAMENTE Y CARGADOS AL SCM",
    12: "HOJAS DE RELEVAMIENTO, EQUIPAMIENTO Y PUESTA A TIERRA DEBIDAMENTE LLENADOS Y CARGADOS AL SCM",
    13: "FOTOS FECHADAS Y NITIDAS DE LA ZONA DE TRABAJO",
    14: "FORMATO DE IDENTIFICACIÓN DE RIESGOS DE LA ZONA DE TRABAJO LLENADO CORRECTAMENTE Y CARGADO AL SCM",
    15: "INFORMACIÓN DE REDES DE SERVICIO PÚBLICO (AGUA, DESAGUE, GAS, TELEFONÍA) Y DE SEMAFORIZACIÓN CARGADOS AL SCM",
    16: "PLANO CUENTA CON ESQUEMAS ORTOGONALES CORRECTOS Y ACTUALIZADOS POR CADA ALIMENTADOR QUE INCLUYA EN EL PROYECTO",
    17: "PLANO PROYECTO CUENTA CON CÓDIGOS DE POSTES, EQUIPOS AÉREOS Y SUBESTACIONES",
    18: "PLANO PROYECTO CUENTA CON DETALLES PARA LA CORRECTA EJECUCIÓN DE LOS TRABAJOS",
    19: "DIBUJO DE PROYECTO ELABORADO CORRECTAMENTE EN AGP",
    20: "CORTES DE VÍAS COORDINADO CON EL MUNICIPIO E INSTITUTO METROPOLITANO DE PLANIFICACIÓN",
    21: "PLANO PROYECTO CUENTA CON TODOS LOS CORTES DE VÍA DONDE SE DISEÑA LA RED (INCLUYE LAS REDES EXISTENTES) Y EN CADA CORTE DE VÍA SE HACE REFERENCIA AL CROQUIS DE INSTALACIÓN",
    22: "SE CUENTA CON PLANO DE SEÑALIZACIÓN Y DESVÍO VEHICULAR",
    23: "DMS CONSIDERADO EN EL DISEÑO DEL PROYECTO Y/O EN EL ESTUDIO DE FACTIBILIDAD (SECCIÓN 23 DEL CNE SUMINISTRO 2011)",
    24: "DISEÑO DE PROYECTO CON TRAZO ADECUADO DE INFRAESTRUCTURA ELÉCTRICA PROYECTADA (REDES, EQUIPOS Y SUBESTACIONES), SEGÚN LAS CONDICIONES EXISTENTES EN CAMPO (ZONA DE TRABAJO)",
    25: "UBICACIÓN DE SUBESTACIÓN DE DISTRIBUCIÓN, EQUIPOS AÉREOS MT Y/O ESTRUCTURAS MT VIABLES, CUMPLIENDO EL CNE SUMINISTRO 2011",
    26: "PROYECTO CIVIL DE SUBESTACIÓN ACORDE CON LO REQUERIDO POR PLUZ (VENTILACIÓN, INGRESO DE EQUIPOS, UBICACIÓN, EQUIPAMIENTO, ETC)",
    27: "TAMAÑO DEL PLANO PROYECTO Y ESCALAS ADECUADAS",
    28: "VALORIZACIÓN CORRECTA DE LA CONEXIÓN Y/O PROYECTO CARGA EN SAP Y/O AGP",
    29: "DISEÑO DE PROYECTO CON TOPOLOGÍA DE RED Y CUMPLIENDO LAS POLICYS VIGENTES",
    30: "PLANO Y/O INFORME CUENTA CON TOMA DE CARGA EN LLAVES (FECHA Y HORA)",
    31: "PLANO Y/O INFORME CUENTA CON TOMA DE TENSIÓN EN BARRA Y EN LOS SUMINISTROS COLA",
    32: "PLANO DE LOTIZACIÓN CARGADO AL SCM",
    33: "INFORME DE FACTIBILIDAD ELABORADO CORRECTAMENTE",
    34: "INFORME DE FACTIBILIDAD CUENTA COMO MÍNIMO CON 2 ALTERNATIVAS PARA ATENCIÓN",
    35: "IDENTIFICACIÓN DE REQUERIMIENTO DE PERMISOS ARQUEOLÓGICOS (CIRA, PMA)",
    36: "IDENTIFICACIÓN DE REQUERIMIENTO DE PERMISOS AMBIENTALES (DIA, OTROS)",
    37: "IDENTIFICACIÓN DE REQUERIMIENTO DE PERMISOS FERROVIARIOS Y VIALES: FERROVIAS CENTRAL, GYM FERROVIAS, METRO DE LIMA LINEA 2, DERECHO DE USO DE VÍAS Y VÍAS CONCESIONADAS TALES COMO RUTAS DE LIMA, NORVIAL, LAMSAC, ETC",
    38: "IDENTIFICACIÓN DE REQUERIMIENTO DE PERMISOS FLUVIALES (AUTORIZACIÓN DEL ANA, POR CRUCES DE RÍOS Y/O ACEQUIAS)",
    39: "IDENTIFICACIÓN DE REQUERIMIENTO DE SERVIDUMBRES Y CONCESIONES"
}

# Mapeo de preguntas que deben pre-seleccionarse como "Sí" por cada tipo de atención.
# La llave es el tipo de atención, el valor es un conjunto (set) de los IDs de preguntas que son "Sí".
# Todas las demás preguntas que no estén listadas aquí se pre-seleccionarán como "N.A.".
DEFAULTS_SI_MAP = {
    "OBRA CIVIL": {1, 2, 5, 6, 9, 23, 25, 26, 27, 28},
    
    "INFORME DE PRE FACTIBILIDAD": {1, 2, 3, 4, 5, 13, 14, 20, 23, 24, 25, 29, 32, 33, 35, 37, 38},
    
    "INFORME DE FACTIBILIDAD": {1, 2, 3, 4, 5, 7, 13, 15, 23, 24, 25, 32, 33, 34},
    
    "REFORMA": {1, 2, 3, 4, 5, 6, 10, 12, 13, 14, 15, 16, 17, 18, 19, 21, 23, 24, 25, 27, 28, 29, 30},
    
    "REFORMA SUSTANCIAL": {1, 2, 3, 4, 5, 6, 7, 12, 13, 14, 16, 17, 18, 19, 21, 23, 24, 25, 27, 28, 29, 30, 31},
    
    "INFORME DE ÁREA": {1, 2, 4, 5, 13, 24, 25, 33}
}

def obtener_checklist_completo(tipo_atencion):
    """
    Retorna la lista completa de las 39 preguntas, cada una con su
    respuesta por defecto ('Sí' o 'N.A.') según el tipo de atención seleccionado.
    """
    tipo_key = str(tipo_atencion).upper().strip()
    si_ids = DEFAULTS_SI_MAP.get(tipo_key, set())
    
    checklist = []
    for q_id, descripcion in sorted(PREGUNTAS_MASTER.items()):
        default_resp = "Sí" if q_id in si_ids else "N.A."
        checklist.append({
            "id": q_id,
            "descripcion": descripcion,
            "respuesta_defecto": default_resp
        })
    return checklist

